### ISSUE TITLE
Как сделать так, чтобы Fenom не ломал сайт?

### ISSUE THREAD

**Issue by sergx** [fenom-template/fenom#308]
По тем или иным причинам может так быть, что парсится код, не предназначенный для Fenom, но содержащий `{`. Было бы очень здорово, если бы вместо ошибки, роняющей страницу, работал бы механизм типа `ignore`, и этот блок не обрабатывался, а выводился бы "как есть". Есть ли в планах внедрить такой механизм? Или может быть уже сейчас есть какая-то настройка типа "soft-mode", позволяющая переключить парсер в щадящий режим?
В частности меня волнует реализация в MODX.

**Comment by pafnuty** [comment]
@sergx 
Надо бы побольше контекста, т.к. не совсем понятно какой код парсится, но мне кажется, что можно посмотреть в сторону https://github.com/fenom-template/fenom/blob/master/docs/ru/ext/extend.md#Расширение-тестового-оператора
либо, если есть возможность, после открывающей скобки ставить новую строку.

**Comment by touol** [comment]
Больше контекста в обсуждении здесь https://modx.pro/help/19203

**Comment by pafnuty** [comment]
Из темы на сайте я понял, что есть две проблемы:
1. Данные, которые приезжают в контенте.
2. Код, который добавляется в шаблон.

В первом случае точно стоит убрать весь контент сайта в `{ignore}` т.к. контент в принципе не должен обрабатываться шаблонизатором ну и никто не мешает вставить валидный тег, который положит сайт.

Во втором - стоит контролировать тот код, который добавляется в шаблон и сделать инструкцию для контент-редакторов или тех людей, которые пользуются такой возможностью. Тут так же никто не запретит вставить валидный тег, который будет ронять производительность сайта например.

Для меня, как человека далёкого от MODX (бэкграунд bitrix и dle и к обоим системам я прикручивал fenom) в целом понятна проблема, я бы тоже очень хотел защитить сайт от поломок со стороны контент-редакторов и "программистов-менеджеров", но как для владельца сайта - я бы сильно надавал по рукам тем контент-редакторам, которые не понимают с какой системой работают и сразу бы выдал нужные инструкции, а ещё лучше записал бы демо как можно и как не стоит делать :)) 

Ну и в коментах был предложен код, который вполне можно попробовать оформить в виде PR и улучшить шаблонизатор, @bzick насколько я знаю, всегда рад улучшениям. Если сделать настраиваемый (на свой страх и риск) уровень обработки ошибок, вероятно это поможет кому-то жить спокойно. 

P.S. JS из тела выносить нужно и это можно сделать в 99,9999% случаев. Есть куча возможностей.

**Comment by touol** [comment]
> Ну и в коментах был предложен код, который вполне можно попробовать оформить в виде PR и улучшить шаблонизатор, @bzick насколько я знаю, всегда рад улучшениям.
В коментах я костыль предложил :-(. Вообще по хорошему, чтоб решить эту проблему, надо бы в феноме сделать опцию, при включении которой, феном, вместо выбрасывания исключения, писал ошибку в лог. И можно было использовать феном так
`
$tpl = $fenom->getRawTemplate()->source($name, $content, true);
$content = $tpl->fetch($properties);
if($tpl->getError()){
...
}
`
В, принципе, я могу сделать такую фичу, но, во первых, надо договориться с разработчиками fenom, что такая фича нужна. Просто так тратить время мне, да и никому, не охота. Во вторых, возможно, потребуются консультации.

**Comment by touol** [comment]
> P.S. JS из тела выносить нужно и это можно сделать в 99,9999% случаев. Есть куча возможностей.
В MODX в теле активно используется JSON и вынести его из тела нельзя.

**Comment by pafnuty** [comment]
@touol ну тогда однозначно не стоит обрабатывать контент шаблонизатором. С этим есть сложности?

**Comment by touol** [comment]
@pafnuty У меня лично с контентом особых проблем не возникало. А вот иногда нужно включить fenom на сайте, который на половину написан другими программистами, и сразу возникают проблемы с JSON и JS. На феноме многие вещи в MODX писать удобнее, чем на его стандартном синтаксисе. То есть, мне удобнее включить феном. А вот синтаксис популярных сниппетов MODX использует JSON. И сайт вылетает. 
Мое мнение, что, если fenom, на тех тегах что не может опознать, вместо исключения пропускал их как они есть, то тогда было бы намного удобнее.

**Comment by Pathologic** [comment]
@pafnuty Все дело в том, что в MODX Revo обработка феномом запускается несколько раз, отсюда и все проблемы у пользователей.

**Comment by touol** [comment]
@Pathologic не вводите в заблуждение. Это не причем. Не корректный тег и феном в любом случае пустую страницу отдаст. Он так устроен.

**Comment by Pathologic** [comment]
@touol Тег ignore для того и предназначен, чтобы обозначить места, которые не должен обрабатывать шаблонизатор, тогда и ошибок никаких не будет. В общем случае, у вас эта проблема будет с любым шаблонизатором, если использовать их так, как сейчас используется феном в рево. Вообще, не смущает, что с этой проблемой приходят только из рево? Что только там в документации написано пробелы после скобок ставить? :smiley:

**Comment by touol** [comment]
> Вообще, не смущает, что с этой проблемой приходят только из рево?

Не смущает. Для других вылет сайта при ошибке в написании тега - это типа се ля ви. Привыкли и о другом не думают. А в MODX, при ошибке в его тегах, тег просто не срабатывает и все. И хочется чтоб при использовании феном было так же.
В самом феноме без MODX ошибки не куда пихать. Ее надо разрабу сообщить и логично вызвать исключение с выводом на страницу типа
`Fatal error: Uncaught exception 'Fenom\Error\UnexpectedTokenException' with message 'Unexpected end of expression' in D:\OpenServer\domains\modx.loc\modMiniIDE\model\vendor\fenom\src\Fenom\Template.php:789 Stack trace: #0 D:\OpenServer\domains\modx.loc\modMiniIDE\model\vendor\fenom\src\Fenom\Compiler.php(102): Fenom\Template->parseExpr(Object(Fenom\Tokenizer)) #1 [internal function]: Fenom\Compiler::ifOpen(Object(Fenom\Tokenizer), Object(Fenom\Tag)) #2 D:\OpenServer\domains\modx.loc\modMiniIDE\model\vendor\fenom\src\Fenom\Tag.php(146): call_user_func('Fenom\\Compiler:...', Object(Fenom\Tokenizer), Object(Fenom\Tag)) #3 D:\OpenServer\domains\modx.loc\modMiniIDE\model\vendor\fenom\src\Fenom\Template.php(651): Fenom\Tag->start(Object(Fenom\Tokenizer)) #4 D:\OpenServer\domains\modx.loc\modMiniIDE\model\vendor\fenom\src\Fenom\Template.php(580): Fenom\Template->parseAct(Object(Fenom\Tokenizer)) #5 D:\OpenServer\domains\modx.loc\modMiniIDE\model\vendor\fenom\src\Fenom\Template.php(274): Fenom\Template->parseTag(Object(Fenom\Toke in main.tpl on line 18`

А в Modx с феном получаем пустую страницу и не информативное сообщение в логах
`pdotools.class.php : 996) Unclosed tag: {if} opened on line 74`

Для Modx много удобней чтоб ошибочные теги выводились как есть. Я 6 лет назад сделал сайт на Modx без феном. Тогда его для MODX не было. Сейчас уже к феном привык и хотел бы его использовать на этом сайте. Но стопудово это его сломает :-(. Там куча и JSON и JS. А если бы феном для Modx выводил ошибочные теги как есть, то я бы сразу там феном и включил :-).

**Comment by pafnuty** [comment]
@touol по диагонали глянул pdoTools https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/_fenom.php
и вижу, что он расширяет стандартные классы фенома https://github.com/bezumkin/pdoTools/blob/cc76f5f786d1a2f2d49ff9fc2335cad7ccf072e6/core/components/pdotools/model/pdotools/_fenom.php#L23-L27
Мне кажется логичнее добавить обработку и пропуск ошибок компиляции в pdoTools.

**Comment by pafnuty** [comment]
https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/pdotools.class.php#L988 вот тут ещё обработка ошибок.

**Comment by Pathologic** [comment]
@touol Между парсером MODX и феномом существует принципиальная разница: первый ищет в шаблоне теги и заменяет их текстом в момент вывода; второй сначала преобразовывает шаблон в php-код, который затем и выполняет вывод. Соответственно если игнорировать ошибки компиляции, то получим на выходе некорректный php-код. Другими словами у вас феном или будет работать или не будет, а так, что местами работает, местами не работает - не получится.

**Comment by touol** [comment]
> Мне кажется логичнее добавить обработку и пропуск ошибок компиляции в pdoTools.

В, принципе, да. Проблемы специфичные для MODX и решать их, по идее, нужно в нем. Я с феном на других CMS не работал. Не знаю пригодиться ли замена исключений логом в них. В чистом феном вроде не пригодиться.
В pdoTools можно расширить класс Template и в нем переписать метод compile, добавить лог и т.д., а в fenomX переписать метод 
`public function getRawTemplate(Template $parent = null)
    {
        return new Template($this, $this->_options, $parent);
    }`
с новым классом.
Так, вообщем, тему здесь @sergx поднял. Я только подключился. И фича может могла пригодиться в самом феноме. И, думаю, самое главная причина почему тема всплывает здесь это то, что issues в https://github.com/bezumkin/pdoTools отключены. Они только PR принимают. И проблема бывает есть и ее не обсудить :-(. Только как до PR своими мозгами дотумкаешь только тогда проблему и можно исправить.

**Comment by Pathologic** [comment]
https://github.com/bezumkin/pdoTools/pull/267/files - вот с этой правкой феном будет работать корректно при правильном подходе.

**Comment by touol** [comment]
> Другими словами у вас феном или будет работать или не будет, а так, что местами работает, местами не работает - не получится.

@Pathologic Однако [вот](https://modx.pro/help/19203#comment-114944) получилось :-)

**Comment by Pathologic** [comment]
@touol Это мало чем отличается от рекомендации пробелы после скобок расставлять.

**Comment by touol** [comment]
@Pathologic фишка в том что не надо везде лазить и пробелы ставить :-). И ignore тоже не надо :-)

**Comment by touol** [comment]
@pafnuty Я что-то не особо разбираюсь в публичных приватных методов класса. https://github.com/touol/pdoTools/blob/master/core/components/pdotools/model/fenom/TemplateX.php Здесь заменил функцию, но нарвался на 

> pdotools.class.php : 993) Unknown method _appendText

То есть, в классе Template полно приватных методов и мне чтоб заменить 1 функцию надо его полностью скопировать? :-(

**Comment by rednakse** [comment]
Это, конечно, сильные ограничения разраба, но можно вызывать приватным методы через Reflection.. Например, вот так:
```
class someClass extends someParentClass
{
	public function someMethod()
	{
		$someProvateMethod new ReflectionMethod('someParentClass', 'privateMethod');
		$someProvateMethod->setAccessible(true);
		$someProvateMethod->invoke($this);
	}
}
```
Это чертовский костыль, но рабочий.

**Comment by touol** [comment]
@rednakse ради правок в 10 строк кода городить огород на 100+ строк?? Как-то не айс. Сделал PR и на [fenom](https://github.com/fenom-template/fenom/pull/309) и на [pdoTools](https://github.com/bezumkin/pdoTools/pull/295). Авось примут :-).

**Comment by sergant210** [comment]
Главная проблема в реализации механизма парсинга.  У MODX он отличается от обычных шаблонизаторов кардинально. Поэтому проблемы в MODX будут с любым шаблонизатором. 
Ну и ещё одна проблема - у фенома только одна скобка для тегов.

**Comment by sergant210** [comment]
> Сделал PR и на fenom и на pdoTools. Авось примут :-).

@touol Я бы на это не рассчитывал. Если здесь ещё есть крошечная вероятность, то про pdoTools забудь. 
Самый лучший выход - сделать пакет, расширяющий pdoTools.
