### ISSUE TITLE
Как целиком выпилить использование eval() из Fenom?

### ISSUE THREAD

**Issue by eugene20237** [fenom-template/fenom#326]
Возможно ли убрать использование функции eval() из шаблонизатора? Что при этом потеряется и как примерно это сделать? Хочу сделать форк без этой функции.

**Comment by WinterSilence** [comment]
@eugene20237 ты конечно можешь заменить eval на include временных php файлов, но что это тебе даст я хз..

**Comment by modxcustomize** [comment]
@WinterSilence привет, а что посоветуете с интеграцией в modx делать?

в modx 3 и php8 вот это ловится:
Fatal error: Uncaught TypeError: Fenom\Render::__construct(): Argument #1 ($fenom) must be of type Fenom, null given, called in /var/www/html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116) : eval()'d code on line 52 and defined in /var/www/html/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Render.php:83 Stack trace: 
#0 /var/www/html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116) : eval()'d code(52): Fenom\Render->__construct(NULL, Object(Closure), Array) 
#1 /var/www/html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116): eval() 
#2 /var/www/html/core/components/pdotools/src/Parsing/Parser.php(69): ModxPro\PdoTools\Parsing\Fenom\Fenom->process('{var $thisId = ...', Array) 
#3 /var/www/html/core/src/Revolution/modResource.php(521): ModxPro\PdoTools\Parsing\Parser->processElementTags('', '{var $thisId = ...', true, false, '[[', ']]', Array, 10) 
#4 /var/www/html/core/src/Revolution/modResource.php(469): MODX\Revolution\modResource->parseContent() 
#5 /var/www/html/core/src/Revolution/modResponse.php(72): MODX\Revolution\modResource->prepare()
 #6 /var/www/html/core/src/Revolution/modRequest.php(154): MODX\Revolution\modResponse->outputContent(Array) 
#7 /var/www/html/core/src/Revolution/modX.php(1242): MODX\Revolution\modRequest->prepareResponse() 
#8 /var/www/html/core/src/Revolution/modX.php(1281): MODX\Revolution\modX->sendForward('2', Array, false) 
#9 /var/www/html/core/src/Revolution/modRequest.php(134): MODX\Revolution\modX->sendErrorPage() 
#10 /var/www/html/core/src/Revolution/modX.php(1499): MODX\Revolution\modRequest->handleRequest() 
#11 /var/www/html/index.php(63): 
MODX\Revolution\modX->handleRequest() 
#12 {main} thrown in /var/www/html/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Render.php on line 83

**Comment by modxcustomize** [comment]
> : Fenom\Render::__construct(): Argument #1 ($fenom) must be of type Fenom, null given

спасибо, [сделал](https://github.com/fenom-template/fenom/issues/340)

**Comment by bzick** [comment]
На неделе выкачу фикс без eval

**Comment by modxcustomize** [comment]
> На неделе выкачу фикс без eval
а [этот баг](https://github.com/fenom-template/fenom/issues/340) не пофиксится?

**Comment by bzick** [comment]
@modxcustomize думаю починю по пути

**Comment by Cheizerman** [comment]
> > : Fenom\Render::__construct(): Argument #1 ($fenom) must be of type Fenom, null given
> 
> спасибо, [сделал](https://github.com/fenom-template/fenom/issues/340)

Hello, please tell me how you solved this problem? I have the same error when I enable pdotools_fenom_cache = Yes

**Comment by bzick** [comment]
in progress
