### ISSUE TITLE
в modx 3 и php8 вот ловится: Fatal error: Uncaught TypeError : Fenom\Render::__construct(): Argument #1 ($fenom) must be of type Fenom, null given

### ISSUE THREAD

**Issue by modxcustomize** [fenom-template/fenom#340]
На php8 в интегрированном Fenom в MODX3 c кодом темплейта:
`{var $thisId = $_modx->resource.content_from_id ?: $_modx->resource.id} {include 'head'} {include 'favicon'} {var $thisId = $_modx->resource.content_from_id ?: $_modx->resource.id}
...
{$thisId | resource : 'longtitle' ?: $thisId | resource : 'pagetitle'}
{$thisId | resource : 'description'}`

страница падает с ошибкой:

```
Fatal error: Uncaught TypeError: Fenom\Render::__construct(): Argument #1 ($fenom) must be of type Fenom, null given, called in /var/www/html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116) : eval()'d code on line 52 and defined in /var/www/html/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Render.php:83 Stack trace: 
#0 /var/www/html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116) : eval()'d code(52): Fenom\Render->__construct(NULL, Object(Closure), Array) 
#1 /var/www/html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116): eval() 
#2 /var/www/html/core/components/pdotools/src/Parsing/Parser.php(69): ModxPro\PdoTools\Parsing\Fenom\Fenom->process('{var $thisId = ...', Array) 
#3 /var/www/html/core/src/Revolution/modResource.php(521): ModxPro\PdoTools\Parsing\Parser->processElementTags('', '{var $thisId = ...', true, false, '[[', ']]', Array, 10) 
#4 /var/www/html/core/src/Revolution/modResource.php(469): MODX\Revolution\modResource->parseContent() 
#5 /var/www/html/core/src/Revolution/modResponse.php(72): MODX\Revolution\modResource->prepare()
 #6 /var/www/html/core/src/Revolution/modRequest.php(154): MODX\Revolution\modResponse->outputContent(Array) 
#7 /var/www/html/core/src/Revolution/modX.php(1242): MODX\Revolution\modRequest->prepareResponse() 
#8 /var/www/html/core/src/Revolution/modX.php(1281): MODX\Revolution\modX->sendForward('2', Array, false) 
#9 /var/www/html/core/src/Revolution/modRequest.php(134): MODX\Revolution\modX->sendErrorPage() 
#10 /var/www/html/core/src/Revolution/modX.php(1499): MODX\Revolution\modRequest->handleRequest() 
#11 /var/www/html/index.php(63): 
MODX\Revolution\modX->handleRequest() 
#12 {main} thrown in /var/www/html/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Render.php on line 83

```

на php7 такого не было :) 
pdoTools самый последний
код сравнивал с тем что имеется на гитхабе - он один в один такой же вроде бы, по крайней мере подстановка этого репо в папку с проектом не приводит к другому результату, а тоже так же падает всё.

**Comment by modxcustomize** [comment]
@bzick Иван привет, просьба не забыть :)

**Comment by bzick** [comment]
В процессе, много надо сделать для php8

**Comment by Cheizerman** [comment]
Hello! Same error on MODX version 3.0.3, php 7.3 did you manage to solve it?

`Fatal error: Uncaught TypeError: Argument 1 passed to Fenom\Render::__construct() must be an instance of Fenom, null given, called in /home/public_html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116) : eval()'d code on line 32 and defined in /home/public_html/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Render.php:83 Stack trace: #0 /home/public_html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116) : eval()'d code(32): Fenom\Render->__construct(NULL, Object(Closure), Array) #1 /home/public_html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116): eval() #2 /home/public_html/core/components/pdotools/src/Parsing/Parser.php(69): ModxPro\PdoTools\Parsing\Fenom\Fenom->process('\r\n\r\n<body>\r\n\r\n ...', Array) #3 /home/public_html/core/src/Revolution/modResource.php(521): ModxPro\PdoTools\Parsing\Parser->processElementTags('', '\r\n\r\n<body>\r\n\r\n ...', true, false, '[[', ']]', Array, 10) #4 /h in /home/public_html/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Render.php on line 83`

**Comment by modxcustomize** [comment]
> Hello! Same error on MODX version 3.0.3, php 7.3 did you manage to solve it?
> 
> `Fatal error: Uncaught TypeError: Argument 1 passed to Fenom\Render::__construct() must be an instance of Fenom, null given, called in /home/public_html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116) : eval()'d code on line 32 and defined in /home/public_html/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Render.php:83 Stack trace: #0 /home/public_html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116) : eval()'d code(32): Fenom\Render->__construct(NULL, Object(Closure), Array) #1 /home/public_html/core/components/pdotools/src/Parsing/Fenom/Fenom.php(116): eval() #2 /home/public_html/core/components/pdotools/src/Parsing/Parser.php(69): ModxPro\PdoTools\Parsing\Fenom\Fenom->process('\r\n\r\n<body>\r\n\r\n ...', Array) #3 /home/public_html/core/src/Revolution/modResource.php(521): ModxPro\PdoTools\Parsing\Parser->processElementTags('', '\r\n\r\n<body>\r\n\r\n ...', true, false, '[[', ']]', Array, 10) #4 /h in /home/public_html/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Render.php on line 83`

it's reported in progress

**Comment by bzick** [comment]
Please use Fenom v3.0.0

**Comment by EMDM45** [comment]
Раз уж тут пошла тема про php 8, добавлю в копилку такую ошибку (точнее предупреждение):

> Creation of dynamic property Fenom\Tokenizer::$curr is deprecated

Версия php - 8.2

**Comment by R2m0x94** [comment]
Тоже ловится лаг
```
Deprecated: Fenom\Template::__construct(): Implicitly marking parameter $parent as nullable is deprecated, the explicit nullable type must be used instead in /var/www/user/data/www/site.ru/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Template.php on line 132

Deprecated: Fenom\Template::parseParams(): Implicitly marking parameter $defaults as nullable is deprecated, the explicit nullable type must be used instead in /var/www/user/data/www/site.ru/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Template.php on line 1587
```
И после того как кэш очищен
```
Deprecated: Fenom::getModifier(): Implicitly marking parameter $template as nullable is deprecated, the explicit nullable type must be used instead in /var/www/user/data/www/site.ru/core/components/pdotools/vendor/fenom/fenom/src/Fenom.php on line 722

Deprecated: Fenom::getTag(): Implicitly marking parameter $template as nullable is deprecated, the explicit nullable type must be used instead in /var/www/user/data/www/site.ru/core/components/pdotools/vendor/fenom/fenom/src/Fenom.php on line 751

Deprecated: Fenom::getRawTemplate(): Implicitly marking parameter $parent as nullable is deprecated, the explicit nullable type must be used instead in /var/www/user/data/www/site.ru/core/components/pdotools/vendor/fenom/fenom/src/Fenom.php on line 947

Deprecated: Fenom\Template::__construct(): Implicitly marking parameter $parent as nullable is deprecated, the explicit nullable type must be used instead in /var/www/user/data/www/site.ru/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Template.php on line 132

Deprecated: Fenom\Template::parseParams(): Implicitly marking parameter $defaults as nullable is deprecated, the explicit nullable type must be used instead in /var/www/user/data/www/site.ru/core/components/pdotools/vendor/fenom/fenom/src/Fenom/Template.php on line 1587
```
- php 8.4.14, 
- modx 3.1.2-pl, 
- pdoTools 3.0.2-pl

**Comment by R2m0x94** [comment]
Следуя фиксам, чтобы убрать ошибку мне пришлось добавить вручную знак `?` в файле Fenom.php
https://dev.to/gromnan/fix-php-84-deprecation-implicitly-marking-parameter-as-nullable-is-deprecated-the-explicit-nullable-type-must-be-used-instead-5gp3
```
- getRawTemplate(Template $parent = null)
+ getRawTemplate(?Template $parent = null)
```
